### ISSUE TITLE
Havoc Chat message position value issue

### ISSUE THREAD

**Issue by halflifefan** [KessieHeldieheren/Havoc-Vision#7]
The default height value is not subtracted from the message height value calculation which caused empty space above the first message while having both position settings set to 1%
![c0d93b4f11b7800f661533cfef89613e](https://user-images.githubusercontent.com/37071910/74097780-787f0c80-4b3a-11ea-83f3-944da82c9162.png)

**Comment by KessieHeldieheren** [comment]
Non-issue.
